version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: django-aws-host-image
    container_name: django-aws-host-container
    ports:
     - "8000:8000"
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/
      - PYTHONBUFFERED=1
